### ISSUE TITLE
Crash after a minute dropping collectibles on someone[Bug] 

### ISSUE THREAD

**Issue by bigdaddy2142** [pierrelasse/YimStuff#13]
### Bug Description

Crash after a minute dropping collectibles on someone

### Steps to Reproduce

Drop collectibles on anyone for about a minute

### Expected Behavior

no crash

### Logs and Screenshots (if applicable)

[06:43:31.4828661][WARN/log_message_error_box.cpp:37] Error Code: Fatal Error

### Version

- [X] The issue exists in the latest version

### Testing Without Scripts

- [ ] The issue does not occur without yimutils and/or SussySpt loaded

**Comment by pierrelasse** [comment]
Could you please upload the entire log for more context?

**Comment by bigdaddy2142** [comment]
> Could you please upload the entire log for more context?

[cout.log](https://github.com/pierrelasse/YimStuff/files/13846434/cout.log)

**Comment by bigdaddy2142** [comment]
Cant seem to recreate it today, yesterday it was every time

**Comment by pierrelasse** [comment]
> Cant seem to recreate it today, yesterday it was every time

Maybe your game was in a bad state. You can close this issue and reopen this when this occurs again.
