### ISSUE TITLE
[Bug] Error report after loading Yim and SussySpt

### ISSUE THREAD

**Issue by heni015** [pierrelasse/YimStuff#17]
### Bug Description

Ater loading Yim sometimes i got errors when loading sussy

### Steps to Reproduce

Idk what's wrong. It's sometimes happens

### Expected Behavior

Repair it.

### Logs and Screenshots (if applicable)

```
%appdata%\YimMenu\scripts\SussySpt.lua:2: attempt to concatenate a function value
stack traceback:
%appdata%\YimMenu\scripts\SussySpt.lua:2: in function 'string.split'
%appdata%\YimMenu\scripts\SussySpt.lua:2: in field 'removeErrorPath'
C:\Users\****l\AppData\Roaming\YimMenu\scripts\SussySpt.lua:2: in function <%appdata%\YimMenu\scripts\SussySpt.lua:2>
0mSussySpt.lua: %appdata%\YimMenu\scripts\SussySpt.lua:2: attempt to concatenate a function value
stack traceback:
%appdata%\YimMenu\scripts\SussySpt.lua:2: in function 'string.split'
%appdata%\YimMenu\scripts\SussySpt.lua:2: in field 'removeErrorPath'
%appdata%\YimMenu\scripts\SussySpt.lua:2: in function <%appdata%\YimMenu\scripts\SussySpt.lua:2>
```

### Version

- [X] The issue exists in the latest version

### Testing Without Scripts

- [X] The issue does not occur without yimutils and/or SussySpt loaded

**Comment by pierrelasse** [comment]
I also had this and I thought I fixed it.
This happens on the minified version only.
I will try fix this in a few hours.

**Comment by pierrelasse** [comment]
It was fixed here: https://github.com/pierrelasse/YimStuff/commit/d89be7185720cb78057931719055d48d806de4ca.
Are you sure you are using the latest version?

**Comment by pierrelasse** [comment]
I can confirm this issue but I'm unable to reproduce it every time.
And it only happens sometimes like you said.

**Comment by pierrelasse** [comment]
Seems to be fixed. Possibly in https://github.com/pierrelasse/YimStuff/commit/c48e86fba9fbdfb67dbe835d551f4f66e35081fb.
