### ISSUE TITLE
[Bug] money MOD doesn't work!

### ISSUE THREAD

**Issue by AlessioSita04** [pierrelasse/YimStuff#18]
### Issue

when I try to give me money from the mod, it doesn't work.
Maybe it's because it isn't patched for the latest version.
Can you please try to fix the issue with a patch?

thanks for all, your script it's beautiful!

**Comment by pierrelasse** [comment]
What did you use to give you money? Online->Money? If so, I also tried it and nothing happenes.

I searched for updated globals, but found none. We will probably have to wait until someone updates them.

**Comment by pierrelasse** [comment]
Fixed in https://github.com/pierrelasse/YimStuff/commit/df37380f67b591ae15dd910689b914a76499a883
