### ISSUE TITLE
[Request]: Clear reports

### ISSUE THREAD

**Issue by 99-99itm** [pierrelasse/YimStuff#7]
### What2Add

HI .. i really like ur scripts .. and ty for ur work .. ik its too much to ask .. but is there any way to change reports ... that would be really helpful .. again ty for u work 
![image](https://github.com/pierrelasse/YimStuff/assets/122922328/636dabb3-9d35-4012-a4a1-74539213c247)

**Comment by pierrelasse** [comment]
Hello,
thanks for the feedback and response.

The displayed reports are not always correct for some reason.

For your request, i will look into how you can effectively delete your existing reports and implement it. Would you also like to be able to set them rather than just clearing them?

Thanks.

**Comment by pierrelasse** [comment]
https://github.com/YimMenu/YimMenu/issues/2582
