### ISSUE TITLE
[Request]: Disable Config->Invisibility hotkey by default

### ISSUE THREAD

**Issue by jvsandhu** [pierrelasse/YimStuff#9]

**Comment by pierrelasse** [comment]
If you want me to disable the menu toggle key from yimmenu, i can't (maybe in theory by patching the memory but na bro).

**Comment by jvsandhu** [comment]
sorry what i am trying to say is hide player/vehicle hotkey in other's tab and the default key is L and on controller the R2 which when pressed enables invisibility of character/ car or you can simple remove that section entirely as it's already in the menu

**Comment by jvsandhu** [comment]
![image](https://github.com/pierrelasse/YimStuff/assets/19775296/df4b710f-dd72-4a35-8d03-46ae3bcb1d6d)

**Comment by pierrelasse** [comment]
Okay, i'm gonna make the hotkey disabled by default so it doesn't annoy controller users or people who accidentally pressed the button.

I will not remove it, because others and me like it and it is better than the native ones.

If this is ok for you, you can close the issue.

**Comment by jvsandhu** [comment]
thanks much appreciated
